import React from 'react'

const page = () => {
    return (
        <div className='px-[6%] py-[3%]'>
            <hr className='border-0 h-[2px] mb-16 bg-one-1' />
            <h1 className='text-center text-six-1 text-5xl pb-5 font-semibold'>About Us</h1>
            <p className='text-four-1 font-semibold text-center'>
                Welcome to Agent, where innovation meets opportunity in the world of front-end development! As a cutting-edge portfolio project, we pride ourselves on revolutionizing the way you discover job listings for front-end developer positions. Our platform is powered by the latest advancements in technology, leveraging MongoDB databases generated by the intelligent ChatGPT. At Agent, we have embarked on a journey to streamline the job-search experience for front-end developers. Our platform is more than just a collection of job listings – it's a testament to the seamless integration of sophisticated technology and user-centric design. Embark on a new chapter in your career with Agent. Explore. Discover. Connect. Whether you are a seasoned professional or just starting your career in front-end development, Agent is here to empower your journey. Let's redefine the way you explore job opportunities – welcome to a platform designed exclusively for front-end developers, by front-end developers. Your future in front-end development awaits!
            </p>

            <hr className='border-0 h-[2px] my-16 bg-one-1' />

            <div className='flex md:flex-row flex-col items-center gap-8'>
                <img src='/img2.png' className='md:w-1/4 sm:w-1/2 w-full' />
                <div className='text-four-5'>
                    <p className='sm:w-3/4 w-full text-four-3 sm:text-4xl text-2xl pb-4 font-semibold'>What Sets Us Apart:</p>
                    <ol className='list-decimal ps-5'>
                        <li>
                            <span className='text-four-3'>Intelligent Database:</span> Our MongoDB database, meticulously crafted by ChatGPT, forms the backbone of our platform. It ensures that you have access to the most relevant and up-to-date job listings in the ever-evolving field of front-end development.
                        </li>
                        <li>
                            <span className='text-four-3'>User-Friendly Interface: </span> Navigating through job opportunities has never been easier. Our intuitive and visually appealing interface allows you to explore a curated collection of front-end developer vacancies effortlessly.
                        </li>
                        <li>
                            <span className='text-four-3'>Tailored for Front-End Developers: </span> We exclusively focus on front-end developer vacancies, providing you with a specialized platform tailored to your expertise. No more sifting through unrelated job listings – our cards showcase opportunities that resonate with your skills and aspirations.
                        </li>
                        <li>
                            <span className='text-four-3'>Innovation at the Core: </span> We believe in staying ahead of the curve. By incorporating the latest technologies and leveraging the power of ChatGPT, we bring you a platform that is not only functional but also at the forefront of technological innovation.
                        </li>
                    </ol>
                </div>
            </div>

            <hr className='border-0 h-[2px] my-16 bg-one-1' />

            <div className='flex md:flex-row flex-col items-center gap-8'>
                <img src='/img3.png' className='md:w-1/4 sm:w-1/2 w-full' />
                <div className='text-four-5'>
                    <p className='sm:w-3/4 w-full text-four-3 sm:text-4xl text-2xl pb-4 font-semibold'>How It Works:</p>
                    <ol className='list-decimal ps-5'>
                        <li>
                            <span className='text-four-3'>Explore:</span> Dive into a curated collection of job cards, each representing a unique front-end developer opportunity.
                        </li>
                        <li>
                            <span className='text-four-3'>Discover: </span> Uncover details about each job listing, including key responsibilities, required skills, and additional information to help you make informed decisions.
                        </li>
                        <li>
                            <span className='text-four-3'>Connect: </span> Seamlessly connect with potential employers and take the next step in your front-end development career.
                        </li>
                    </ol>
                </div>
            </div>

            <hr className='border-0 h-[2px] mt-16 bg-one-1' />

            <h2 className='text-base text-four-1 font-semibold pt-8'>Join Us in Shaping the Future of Front-End Development!</h2>

        </div>
    )
}

export default page;